import 'package:uuid/uuid.dart';

import '../../../core/algorithms/event_discovery.dart';
import '../../../core/algorithms/memory_scoring.dart';
import '../../../core/algorithms/memory_title_generator.dart';
import '../../../core/algorithms/best_photo_selector.dart';
import '../../../core/algorithms/cover_photo_selector.dart';
import '../../../core/algorithms/automatic_album_generator.dart';
import '../../../core/database/daos/memory_dao.dart';
import '../../../core/database/daos/photo_metadata_dao.dart';
import '../../../core/database/daos/face_dao.dart';
import '../../../core/logging/app_logger.dart';
import '../../../domain/models/memory/memory.dart';
import '../../../domain/models/memory/automatic_album.dart';

class MemoryService {
  MemoryService({
    required MemoryDao memoryDao,
    required PhotoMetadataDao metadataDao,
    required FaceDao faceDao,
    required AppLogger logger,
  })  : _memoryDao = memoryDao,
        _metadataDao = metadataDao,
        _faceDao = faceDao,
        _logger = logger;

  final MemoryDao _memoryDao;
  final PhotoMetadataDao _metadataDao;
  final FaceDao _faceDao;
  final AppLogger _logger;
  final _uuid = const Uuid();

  Future<List<Memory>> generateMemories({
    int batchSize = 500,
    Set<String>? existingMemoryIds,
  }) async {
    _logger.info('Starting memory generation (batch size: $batchSize)');

    final allMetadata = await _metadataDao.getAll();
    if (allMetadata.isEmpty) {
      _logger.info('No indexed photos found');
      return [];
    }

    final photoTimestamps = <(String, DateTime)>[];
    for (final meta in allMetadata) {
      if (meta.dateCreated != null) {
        photoTimestamps.add((meta.photoId, meta.dateCreated!));
      }
    }

    if (photoTimestamps.length < EventDiscovery.minPhotos) {
      _logger.info('Not enough photos with dates (${photoTimestamps.length})');
      return [];
    }

    _logger.info('Discovering events from ${photoTimestamps.length} photos');
    final clusters = EventDiscovery.discoverEnhanced(
      photoTimestamps: photoTimestamps,
    );
    _logger.info('Found ${clusters.length} clusters');

    if (clusters.isEmpty) return [];

    final qualityScores = <String, double>{};
    final peoplePresence = <String, bool>{};
    final gpsData = <String, (double, double)>{};

    for (final meta in allMetadata) {
      if (meta.qualityScore != null) {
        qualityScores[meta.photoId] = meta.qualityScore!;
      }
      if (meta.latitude != null && meta.longitude != null) {
        gpsData[meta.photoId] = (meta.latitude!, meta.longitude!);
      }
    }

    // Batch faces lookup to avoid N+1 per-photo queries
    final allClusterPhotoIds = clusters.expand((c) => c.photoIds).toSet();
    final facesByPhoto = await _faceDao.getFacesByPhotoIds(allClusterPhotoIds);
    for (final photoId in allClusterPhotoIds) {
      peoplePresence[photoId] = (facesByPhoto[photoId]?.isNotEmpty ?? false);
    }

    _logger.info('Scoring ${clusters.length} candidates');
    final candidates = MemoryScoring.scoreCandidates(
      clusters: clusters,
      qualityScores: qualityScores,
      peoplePresence: peoplePresence,
      gpsData: gpsData,
    );
    _logger.info('${candidates.length} candidates passed scoring threshold');

    final memories = <Memory>[];
    for (final candidate in candidates) {
      final titleResult = MemoryTitleGenerator.generate(candidate: candidate);

      final photoScores = BestPhotoSelector.scorePhotos(
        photoIds: candidate.photoIds,
        qualityScores: qualityScores,
      );

      final coverPhotoId = CoverPhotoSelector.selectCover(
        photoScores: photoScores,
        peoplePresence: peoplePresence,
      );

      final personIds = <String>[];
      final seenPersonIds = <String>{};
      for (final photoId in candidate.photoIds) {
        final faces = facesByPhoto[photoId] ?? const [];
        for (final face in faces) {
          final pid = face.personId;
          if (pid != null && seenPersonIds.add(pid)) {
            personIds.add(pid);
          }
        }
      }

      final now = DateTime.now();
      final memory = Memory(
        memoryId: _uuid.v4(),
        title: titleResult.title,
        subtitle: titleResult.subtitle,
        photoIds: candidate.photoIds,
        coverPhotoId: coverPhotoId,
        startDate: candidate.cluster.startDate,
        endDate: candidate.cluster.endDate,
        score: candidate.overallScore,
        theme: MemoryTheme.values.firstWhere(
          (t) => t.name == titleResult.theme,
          orElse: () => MemoryTheme.everyday,
        ),
        createdAt: now,
        updatedAt: now,
        isAutoGenerated: true,
        personIds: personIds,
        dayOfWeek: candidate.cluster.startDate.weekday,
        month: candidate.cluster.startDate.month,
        year: candidate.cluster.startDate.year,
      );

      memories.add(memory);
    }

    _logger.info('Persisting ${memories.length} memories');
    await _memoryDao.insertMemories(memories);

    final albums = AutomaticAlbumGenerator.generate(memories: memories);
    _logger.info('Generated ${albums.length} automatic albums');
    await _memoryDao.insertAutomaticAlbums(albums);

    return memories;
  }

  Future<List<Memory>> getActiveMemories() async {
    return _memoryDao.getActiveMemories();
  }

  Future<List<AutomaticAlbum>> getVisibleAlbums() async {
    return _memoryDao.getVisibleAutomaticAlbums();
  }

  Future<void> hideMemory(String memoryId) async {
    await _memoryDao.updateMemoryStatus(memoryId, MemoryStatus.hidden);
  }

  Future<void> dismissMemory(String memoryId) async {
    await _memoryDao.updateMemoryStatus(memoryId, MemoryStatus.dismissed);
  }

  Future<void> hideAlbum(String albumId) async {
    await _memoryDao.hideAutomaticAlbum(albumId);
  }

  Future<void> showAlbum(String albumId) async {
    await _memoryDao.showAutomaticAlbum(albumId);
  }

  Future<void> refreshMemories() async {
    _logger.info('Refreshing memories');
    await generateMemories();
  }

  Future<int> getMemoryCount() async {
    return _memoryDao.getActiveMemoryCount();
  }
}
