/// Domain model representing an automatically generated memory.
enum MemoryStatus {
  active,
  hidden,
  dismissed,
}

enum MemoryTheme {
  trip,
  birthday,
  seasonal,
  event,
  people,
  milestone,
  everyday,
}

class Memory {
  final String memoryId;
  final String title;
  final String? subtitle;
  final List<String> photoIds;
  final String coverPhotoId;
  final DateTime startDate;
  final DateTime endDate;
  final double score;
  final MemoryTheme theme;
  final MemoryStatus status;
  final DateTime createdAt;
  final DateTime updatedAt;
  final bool isAutoGenerated;
  final String? locationLabel;
  final List<String> personIds;
  final int? dayOfWeek;
  final int? month;
  final int? year;

  const Memory({
    required this.memoryId,
    required this.title,
    this.subtitle,
    required this.photoIds,
    required this.coverPhotoId,
    required this.startDate,
    required this.endDate,
    required this.score,
    required this.theme,
    this.status = MemoryStatus.active,
    required this.createdAt,
    required this.updatedAt,
    this.isAutoGenerated = true,
    this.locationLabel,
    this.personIds = const [],
    this.dayOfWeek,
    this.month,
    this.year,
  });

  int get photoCount => photoIds.length;

  bool get isActive => status == MemoryStatus.active;

  Duration get duration => endDate.difference(startDate);

  bool get isMultiDay => duration.inDays > 0;

  Memory copyWith({
    String? memoryId,
    String? title,
    String? subtitle,
    List<String>? photoIds,
    String? coverPhotoId,
    DateTime? startDate,
    DateTime? endDate,
    double? score,
    MemoryTheme? theme,
    MemoryStatus? status,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isAutoGenerated,
    String? locationLabel,
    List<String>? personIds,
    int? dayOfWeek,
    int? month,
    int? year,
  }) {
    return Memory(
      memoryId: memoryId ?? this.memoryId,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      photoIds: photoIds ?? this.photoIds,
      coverPhotoId: coverPhotoId ?? this.coverPhotoId,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      score: score ?? this.score,
      theme: theme ?? this.theme,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      locationLabel: locationLabel ?? this.locationLabel,
      personIds: personIds ?? this.personIds,
      dayOfWeek: dayOfWeek ?? this.dayOfWeek,
      month: month ?? this.month,
      year: year ?? this.year,
    );
  }

  Map<String, Object?> toMap() {
    return {
      'memory_id': memoryId,
      'title': title,
      'subtitle': subtitle,
      'photo_ids': photoIds.join(','),
      'cover_photo_id': coverPhotoId,
      'start_date': startDate.toIso8601String(),
      'end_date': endDate.toIso8601String(),
      'score': score,
      'theme': theme.index,
      'status': status.index,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'location_label': locationLabel,
      'person_ids': personIds.join(','),
      'day_of_week': dayOfWeek,
      'month': month,
      'year': year,
    };
  }

  factory Memory.fromMap(Map<String, Object?> row) {
    return Memory(
      memoryId: row['memory_id'] as String,
      title: row['title'] as String,
      subtitle: row['subtitle'] as String?,
      photoIds: (row['photo_ids'] as String).split(',').where((s) => s.isNotEmpty).toList(),
      coverPhotoId: row['cover_photo_id'] as String,
      startDate: DateTime.parse(row['start_date'] as String),
      endDate: DateTime.parse(row['end_date'] as String),
      score: row['score'] as double,
      theme: MemoryTheme.values[row['theme'] as int],
      status: MemoryStatus.values[row['status'] as int],
      createdAt: DateTime.parse(row['created_at'] as String),
      updatedAt: DateTime.parse(row['updated_at'] as String),
      isAutoGenerated: (row['is_auto_generated'] as int) == 1,
      locationLabel: row['location_label'] as String?,
      personIds: (row['person_ids'] as String? ?? '').split(',').where((s) => s.isNotEmpty).toList(),
      dayOfWeek: row['day_of_week'] as int?,
      month: row['month'] as int?,
      year: row['year'] as int?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Memory && runtimeType == other.runtimeType && memoryId == other.memoryId;

  @override
  int get hashCode => memoryId.hashCode;
}
