import '../models/gallery_action.dart';
import 'action_registry.dart';
import '../../../core/database/app_database.dart';
import '../../../domain/models/smart_album.dart';
import '../../../domain/models/memory/memory.dart';
import '../../../core/logging/app_logger.dart';

/// Executes validated gallery actions.
///
/// All actions require user confirmation before execution.
/// Destructive actions (delete) require double confirmation.
class ActionExecutor {
  ActionExecutor({
    required AppDatabase database,
    required ActionRegistry registry,
    AppLogger? logger,
  })  : _database = database,
        _registry = registry,
        _logger = logger;

  final AppDatabase _database;
  final ActionRegistry _registry;
  final AppLogger? _logger;

  /// Execute an action after validation.
  Future<ExecutionResult> execute(GalleryAction action) async {
    final validation = _registry.validate(action);
    if (!validation.isValid) {
      return ExecutionResult.failure('Invalid action: ${validation.error}');
    }

    try {
      switch (action.type) {
        case GalleryActionType.createSmartAlbum:
          return await _createSmartAlbum(action);
        case GalleryActionType.createMemory:
          return await _createMemory(action);
        case GalleryActionType.addFavorites:
          return await _addFavorites(action);
        case GalleryActionType.removeFavorites:
          return await _removeFavorites(action);
        case GalleryActionType.deletePhotos:
          return await _deletePhotos(action);
        case GalleryActionType.openPhoto:
        case GalleryActionType.openPerson:
        case GalleryActionType.openEvent:
        case GalleryActionType.openAlbum:
        case GalleryActionType.showSearchResults:
        case GalleryActionType.openEditor:
          return ExecutionResult.navigation(action);
      }
    } catch (e, st) {
      _logger?.error('Action execution failed', error: e, stackTrace: st);
      return ExecutionResult.failure('Execution failed: $e');
    }
  }

  Future<ExecutionResult> _createSmartAlbum(GalleryAction action) async {
    final title = action.albumTitle ?? 'Untitled';
    final photoIds = action.photoIds;
    final now = DateTime.now();

    final album = SmartAlbum(
      albumId: 'album_${now.millisecondsSinceEpoch}',
      title: title,
      category: SmartAlbumCategory.allPhotos,
      query: SmartAlbumQuery(
        objectTags: null,
        personIds: null,
      ),
      createdAt: now,
      updatedAt: now,
    );

    await _database.smartAlbums.upsert(album);

    return ExecutionResult.success(
      'Created album "$title" with ${photoIds.length} photos.',
      data: {'albumId': album.albumId},
    );
  }

  Future<ExecutionResult> _createMemory(GalleryAction action) async {
    final title = action.memoryTitle ?? 'My Memory';
    final photoIds = action.photoIds;
    final now = DateTime.now();

    final memory = Memory(
      memoryId: 'memory_${now.millisecondsSinceEpoch}',
      title: title,
      photoIds: photoIds,
      coverPhotoId: photoIds.isNotEmpty ? photoIds.first : '',
      startDate: now.subtract(const Duration(days: 365)),
      endDate: now,
      score: 1.0,
      theme: MemoryTheme.everyday,
      createdAt: now,
      updatedAt: now,
      isAutoGenerated: false,
    );

    await _database.memories.insertMemory(memory);

    return ExecutionResult.success(
      'Created memory "$title" with ${photoIds.length} photos.',
    );
  }

  Future<ExecutionResult> _addFavorites(GalleryAction action) async {
    final photoIds = action.photoIds;
    int added = 0;

    for (final photoId in photoIds) {
      try {
        await _database.favorites.add(photoId);
        added++;
      } catch (_) {}
    }

    return ExecutionResult.success('Added $added photos to favorites.');
  }

  Future<ExecutionResult> _removeFavorites(GalleryAction action) async {
    final photoIds = action.photoIds;
    int removed = 0;

    for (final photoId in photoIds) {
      try {
        await _database.favorites.remove(photoId);
        removed++;
      } catch (_) {}
    }

    return ExecutionResult.success('Removed $removed photos from favorites.');
  }

  Future<ExecutionResult> _deletePhotos(GalleryAction action) async {
    final photoIds = action.photoIds;
    return ExecutionResult.confirmationRequired(
      'Are you sure you want to delete ${photoIds.length} photos? This cannot be undone.',
      data: {'photoIds': photoIds},
    );
  }
}

/// Result of executing a gallery action.
class ExecutionResult {
  final bool success;
  final String message;
  final ExecutionType type;
  final Map<String, dynamic>? data;

  const ExecutionResult._({
    required this.success,
    required this.message,
    required this.type,
    this.data,
  });

  factory ExecutionResult.success(String message, {Map<String, dynamic>? data}) {
    return ExecutionResult._(
      success: true,
      message: message,
      type: ExecutionType.completed,
      data: data,
    );
  }

  factory ExecutionResult.failure(String message) {
    return ExecutionResult._(
      success: false,
      message: message,
      type: ExecutionType.failed,
    );
  }

  factory ExecutionResult.confirmationRequired(String message,
      {Map<String, dynamic>? data}) {
    return ExecutionResult._(
      success: false,
      message: message,
      type: ExecutionType.confirmationRequired,
      data: data,
    );
  }

  factory ExecutionResult.navigation(GalleryAction action) {
    return ExecutionResult._(
      success: true,
      message: 'Navigate to ${action.type.name}',
      type: ExecutionType.navigation,
    );
  }
}

enum ExecutionType {
  completed,
  failed,
  confirmationRequired,
  navigation,
}
